# Generated by Django 5.2.1 on 2026-01-30 15:30

import django.db.models.deletion
import funcionarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subdireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('piso', models.PositiveSmallIntegerField(default=1, verbose_name='Piso')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subdirección',
                'verbose_name_plural': 'Subdirecciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('subdireccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='funcionarios.subdireccion', verbose_name='Subdirección')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['subdireccion__nombre', 'nombre'],
                'unique_together': {('subdireccion', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='funcionarios.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['departamento__subdireccion__nombre', 'departamento__nombre', 'nombre'],
                'unique_together': {('departamento', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='Formato: 12345678-9', max_length=12, unique=True, validators=[funcionarios.models.validate_rut], verbose_name='RUT')),
                ('nombre_funcionario', models.CharField(max_length=180, verbose_name='Nombre Completo')),
                ('anexo', models.CharField(blank=True, default='', help_text='Número de anexo telefónico', max_length=10, verbose_name='Anexo')),
                ('numero_publico', models.CharField(blank=True, editable=False, help_text='Se calcula automáticamente: 227263 + anexo', max_length=32, verbose_name='Número Público')),
                ('cargo', models.CharField(blank=True, default='', max_length=120, verbose_name='Cargo')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='funcionarios.departamento', verbose_name='Departamento')),
                ('subdireccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='funcionarios.subdireccion', verbose_name='Subdirección')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='funcionarios.unidad', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['nombre_funcionario'],
                'indexes': [models.Index(fields=['rut'], name='funcionario_rut_aec88c_idx'), models.Index(fields=['nombre_funcionario'], name='funcionario_nombre__4972c4_idx'), models.Index(fields=['anexo'], name='funcionario_anexo_89755e_idx')],
            },
        ),
    ]
