# Generated by Django 5.2.1 on 2026-02-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('type', models.CharField(choices=[('B/N', 'Blanco y negro'), ('COLOR', 'Color')], default='B/N', max_length=10)),
                ('community', models.CharField(default='public', max_length=128)),
                ('snmp_port', models.PositiveIntegerField(default=161)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('last_ok', models.BooleanField(null=True)),
                ('last_message', models.TextField(blank=True)),
                ('last_black', models.FloatField(blank=True, null=True)),
                ('last_cyan', models.FloatField(blank=True, null=True)),
                ('last_magenta', models.FloatField(blank=True, null=True)),
                ('last_yellow', models.FloatField(blank=True, null=True)),
                ('last_errors', models.JSONField(blank=True, default=list)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('last_connected', models.BooleanField(blank=True, null=True)),
                ('last_woke', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Impresora',
                'verbose_name_plural': 'Impresoras',
                'ordering': ['name'],
            },
        ),
    ]
